# Pandas

- **Pandas** is a powerful data manipulation and analysis library in Python.
- It is widely used for:
  - Data analysis
  - Data cleaning
  - Data manipulation

## Primary Data Structures

Pandas provides two main data structures:

### 1. Series

- A **one-dimensional** array-like object.
- Stores a single column of data.
- Each element has an associated index (label).

### 2. DataFrame

- A **two-dimensional**, size-mutable, and potentially heterogeneous tabular data structure.
- Organized into **rows and columns** with labeled axes.
- Can store different data types in different columns.

## Comparison

| Feature | Series | DataFrame |
|---------|--------|-----------|
| Dimension | 1D | 2D |
| Structure | Single column | Rows and columns |
| Data Types | Usually one type | Multiple data types |
| Index | One axis (rows) | Two axes (rows and columns) |

In [1]:
# Install pandas in Jupyter Notebook

!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in H:\mlCode\python\venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in H:\mlCode\python\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in H:\mlCode\python\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.8 MB 2.1 MB/s eta 0:00:05
   ----- ---------------------------------- 1.3/9.8 MB 2.0 MB/s eta 0:00:05
   ------ --------------------------------- 1.6/9.8 MB 2.0 MB/s eta 0:00:05
   -------- ------------------------------- 2.1/9.8 MB 2.0 MB/s eta 0:00:04
   --------- ------------------------------ 2.4/9.8 MB 1.9 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.8 MB 1.9 MB/s eta 0:00:04
   ------------ --------------------------- 3.1/9.8 MB 1.9 MB/s eta 0:00:04
   --------------- ------------------------ 3.7/9.8 MB 1.9 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 1.9 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.8 MB 1.9 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.8 MB 1.9 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.8 MB 1.9 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.8 MB 1.8 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.9 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.8 MB 1.9 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 7.1/9.8 MB 1.9 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.8 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.8 MB 1.9 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.8 MB 1.9 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 1.8 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.8 MB/s  0:00:05
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

In [2]:
import pandas as pd

## 01. Series

In [9]:
# A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table

data = [1, 2, 3, 4, 5]
series = pd.Series(data)

print("Series \n", series)    # left side : default indexes  | right side : values
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [10]:
# Create a Series from dictionary

data = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [12]:
# Marge data and index 

data = [10,20,30]
index = ['a', 'b', 'c']

print(pd.Series(data, index=index))

a    10
b    20
c    30
dtype: int64

## 02. DataFrame

In [13]:
# Create a dataframe from a dictionary of list

data = {
    'Name' : ['Riad', 'Sajib', 'Shakib'],
    'Age' : [25, 26, 23],
    'City' : ['Dhaka', 'Rajshahi', 'Joypurhat']
}

df = pd.DataFrame(data)

print(df)
print(type(df))

     Name  Age       City
0    Riad   25      Dhaka
1   Sajib   26   Rajshahi
2  Shakib   23  Joypurhat
<class 'pandas.DataFrame'>

In [15]:
import numpy as np

print(np.array(df))

[['Riad' 25 'Dhaka']
 ['Sajib' 26 'Rajshahi']
 ['Shakib' 23 'Joypurhat']]

In [66]:
# Create a Data frame From a List of Dictionaries

data = [
    {'Name': 'Riad', 'Age': 25, 'City': 'Dhaka'},
    {'Name': 'Sajib', 'Age': 26, 'City': 'Rajshahi'},
    {'Name': 'Shakib', 'Age': 23, 'City': 'Joypurhat'},
    {'Name': 'Pritom', 'Age': 26, 'City': 'Bogura'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0    Riad   25      Dhaka
1   Sajib   26   Rajshahi
2  Shakib   23  Joypurhat
3  Pritom   26     Bogura
<class 'pandas.DataFrame'>

In [17]:
# Print Top 5 element from Existing csv file

df = pd.read_csv('Online Sales Data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [19]:
# Print last 5 element from Existing csv file

df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
16,10017,2024-01-17,Beauty Products,Dyson Supersonic Hair Dryer,1,399.99,399.99,Europe,PayPal
17,10018,2024-01-18,Sports,Manduka PRO Yoga Mat,4,119.99,479.96,Asia,Credit Card
18,10019,2024-01-19,Electronics,Garmin Forerunner 945,2,499.99,999.98,North America,Credit Card
19,10020,2024-01-20,Home Appliances,Ninja Professional Blender,1,99.99,99.99,Europe,PayPal
20,10021,2024-01-21,Clothing,Zara Summer Dress,3,50.00,150.00,Asia,Debit Card

In [81]:
df.head(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card

In [78]:
# Display the data types of each column

print("Data types:\n", df.dtypes)

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object

In [79]:
# Describe the DataFrame

df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       21.000000   21.000000    21.000000      21.000000
mean     10011.000000    2.380952   364.180952     593.501429
std          6.204837    1.430950   559.186595     680.552514
min      10001.000000    1.000000    15.990000      51.980000
25%      10006.000000    1.000000    69.990000     129.990000
50%      10011.000000    2.000000   129.990000     399.990000
75%      10016.000000    3.000000   499.990000     599.970000
max      10021.000000    6.000000  2499.990000    2499.990000

In [86]:
# Another great option: Group by 'Product Category' and find total 'Units Sold'

grouped_units = df.groupby('Product Category')['Units Sold'].sum()

print("Total units sold by category:\n", grouped_units)

Total units sold by category:
 Product Category
Beauty Products     3
Books               9
Clothing           14
Electronics         7
Home Appliances     5
Sports             12
Name: Units Sold, dtype: int64

#### Accessing Data from DataFrame

In [22]:
df

     Name  Age       City
0    Riad   25      Dhaka
1   Sajib   26   Rajshahi
2  Shakib   23  Joypurhat
3  Pritom   26     Bogura

In [25]:
# Accessing Attributes

print(df['Name'])

print(type(df['Name']))

0      Riad
1     Sajib
2    Shakib
3    Pritom
Name: Name, dtype: str
<class 'pandas.Series'>

In [36]:
# Accessing Row

df.loc[1]    # loc[row]  | loc = location

Name       Sajib
Age           26
City    Rajshahi
Name: 1, dtype: object

In [35]:
# Accessing Specific Cell Data

print(df.iloc[0,0])   # Riad     |   iloc = index location
print(df.iloc[3,2])   # Bogura

Riad
Bogura

In [40]:
# Accessing Specific Element
 
print(df.at[2, 'City'] )    # 2nd row of City
print(df.at[3, 'Age'] )    # 3rd row of Age

Joypurhat
26

In [ ]:
# Another way - using "iat"

df.iat[0,2]   # iat[row, col]

'Dhaka'

## 03. Data Manipulation with DataFrame

In [44]:
df

     Name  Age       City
0    Riad   25      Dhaka
1   Sajib   26   Rajshahi
2  Shakib   23  Joypurhat
3  Pritom   26     Bogura

In [67]:
# Adding a Column

df['Salary'] = [40000, 35000, 45000, 35000]

df

     Name  Age       City  Salary
0    Riad   25      Dhaka   40000
1   Sajib   26   Rajshahi   35000
2  Shakib   23  Joypurhat   45000
3  Pritom   26     Bogura   35000

####  X-Axis = Row = 0    
####  Y-Axis = Column = 1

In [52]:
# Remove a column  (Temporary)

df.drop('Salary',axis=1)     # Salary is a column

# drop is not permanent operation. So not removed permanently

     Name  Age       City
0    Riad   25      Dhaka
1   Sajib   26   Rajshahi
2  Shakib   23  Joypurhat
3  Pritom   26     Bogura

In [57]:
# Prove of Temporary Deletion
df

     Name  Age       City
0    Riad   25      Dhaka
1   Sajib   26   Rajshahi
2  Shakib   23  Joypurhat
3  Pritom   26     Bogura

In [68]:
# Remove a column Permanently

# inplace = 1

df.drop('Salary', axis=1, inplace = True)

df

     Name  Age       City
0    Riad   25      Dhaka
1   Sajib   26   Rajshahi
2  Shakib   23  Joypurhat
3  Pritom   26     Bogura

In [69]:
## Add(+)  with Column

df["Age"] = df['Age'] + 5
df

     Name  Age       City
0    Riad   30      Dhaka
1   Sajib   31   Rajshahi
2  Shakib   28  Joypurhat
3  Pritom   31     Bogura

In [70]:
# Remove a Row Permanently

df.drop(2, inplace=True)

df

     Name  Age      City
0    Riad   30     Dhaka
1   Sajib   31  Rajshahi
3  Pritom   31    Bogura